#!/bin/bash
if [ "$1" == "container" ]; then
  source /venv/bin/activate
  pip install PyYAML
  shift
  python `pwd`/runner/yrunc.py $*
else
  python3 -m venv /tmp/venv
  source /tmp/venv/bin/activate
  python3 -m pip install --upgrade pip
  pip install PyYAML requests
  python3 `pwd`/runner/yrunv.py $*
fi
