#FROM alpine:latest
FROM alpine:edge as base
RUN echo "************* [0] RUNNING BASE *****************"
RUN apk update && apk add --no-cache python3 py3-greenlet libxml2 libxslt libjpeg celery redis net-tools iproute2 ncdu which openssh libcurl unzip libssl3 ca-certificates openrc bash
RUN apk add --virtual build-deps build-base linux-headers swig python3-dev musl-dev jpeg-dev zlib-dev poetry grep git wget curl nodejs npm
WORKDIR /
RUN mkdir /app

FROM base as nodejs
RUN echo "************* [0:1] RUNNING NODE *****************"
WORKDIR /app
RUN npm install -D tailwindcss esbuild @tailwindcss/typography concurrently

FROM nodejs as python
RUN echo "************* [0:2] RUNNING PYTHON *****************"
ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=1 \
  PIP_DISABLE_PIP_VERSION_CHECK=1 \
  PIP_DEFAULT_TIMEOUT=100
RUN python -m venv /venv
ENV PATH="/venv/bin:/bin:$PATH"
RUN source /venv/bin/activate
RUN python -m pip install --upgrade pip
RUN pip install PyMuPDFb
RUN pip install tzdata
RUN pip install poetry-plugin-export
COPY ./pyproject.toml /app
RUN poetry export --without-hashes --with dev -f requirements.txt -o requirements.txt
RUN cat requirements.txt | grep -v 'greenlet' | sed 's/==.*//' > r2.txt
RUN mv r2.txt requirements.txt
RUN pip install --no-cache-dir --no-deps -r requirements.txt
WORKDIR /
RUN mkdir /data
RUN mkdir /data/database
RUN echo "************* DONE: PYTHON PACKAGES *****************"

FROM python as final
RUN echo "************* [2:4] RUNNING TRANSLATIONS *****************"
#RUN git clone https://github.com/s-i-e-v-e/ambuda /app
#RUN git switch podman
COPY ./ /app
WORKDIR /app
RUN ./ar i18n
RUN echo "************* [1:3] RUNNING NPX *****************"
RUN npx tailwindcss -i /app/ambuda/static/css/style.css -o /app/ambuda/static/gen/style.css --minify
RUN npx esbuild /app/ambuda/static/js/main.js --outfile=/app/ambuda/static/gen/main.js --bundle --minify
RUN echo "************* PODMAN IMAGE BUILT *****************"
