apiVersion: v1
kind: Pod
metadata:
  name: deploy
spec:
  restartPolicy: Never
  containers:
    - name: ambuda
      image: ${AMBUDA_IMAGE}
      ports:
        - containerPort: 5000
          hostPort: ${HOST_PORT}
          hostIP: "${HOST_IP}"
          protocol: TCP
      resources: { }
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: { }
        privileged: false
        readOnlyRootFilesystem: false
        seLinuxOptions: { }
      workingDir: /ambuda/app
      command: ${CMD}
      volumeMounts:
        - mountPath: /ambuda/data
          name: data
  volumes:
    - name: data
      hostPath:
        path: ${HOST_DATA_DIR}
        type: Directory
status: { }
